import:
  - ~/.config/awesome/apps/alacritty/colors.yml

font:
  normal:
    family: Iosevka Nerd Font
    # family: SAGA
    # family: FantasqueSansMono Nerd Font
    # family: JetBrainsMono Nerd Font
    # family: Victor Mono Nerd Font
    style: Medium Italic
  size: 18

window:
  padding:
    x: 50
    y: 50
    dynamic_padding: true

live_config_reload: true

cursor:
  style: Beam
  vi_style_cursor: Beam
